<a href="https://colab.research.google.com/github/syarifahkemala/learn-numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
a[0]

1

In [ ]:
a[1]

2

In [ ]:
a = np.array([[1,2],[3,4],[5,6]]) #array 2 dimensi
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a.ndim #cek jumlah dimensi yang ada di array

6

In [ ]:
a.itemsize #jumlah byte per elemen

8

In [ ]:
a.size #cek jumlah elemen yang ada di array

6

In [ ]:
a.shape #cek dimensi array : 3 row dan 2 column

(3, 2)

In [ ]:
np.arange(1,5) # buat list array dari 1 hingga 5 namun tidak termasuk 5

array([1, 2, 3, 4])

In [ ]:
np.arange(1,5,2) #buat list array dari 1 hingga 5 namun diberi jarak 2 angka

array([1, 3])

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a.shape

(3, 2)

In [ ]:
a.reshape(2,3) #mengubah dimensi array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [ ]:
a[2,2]

2

In [ ]:
a[1,0:3]

array([1, 2, 3])

In [ ]:
for row in a:
  print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [ ]:
#flattening
for cell in a.flat:
  print(cell)

6
7
8
1
2
3
9
3
2


In [ ]:
#Stcking 2 array

a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

In [ ]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [ ]:
# split array
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
result = np.hsplit(a,3)

In [ ]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [ ]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [ ]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [ ]:
# Indexing with boolean
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
a[b]= -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [ ]:
a =np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for cell in a.flatten():
  print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for x in np.nditer(a, order = "C"):
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for x in np.nditer(a, order = "f"):
  print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [ ]:
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [ ]:
for x,y in np.nditer([a,b]):
  print(x,y)

0 3
1 3
16 3
81 3
256 7
625 7
1296 7
2401 7
4096 11
6561 11
10000 11
14641 11


In [ ]:
arr = [1,2,3,4,5,6,7,8,9]


In [ ]:
print(-len(arr))

-9


In [ ]:
arr = [1,2,3,4,5,6,7,8,9]
expected = []
i = -1
while i >= -len(arr) :
  expected.append(arr[i])
  i -= 1

In [ ]:
expected

[9, 8, 7, 6, 5, 4, 3, 2, 1]